sudo: false
language: node_js
cache:
  directories:
    - node_modules
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
branches:
  only:
    - main
notifications:
  email: false
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run release
