
language: node_js

after_success:
  - npm run report-coverage

branches:
  only:
    - main

jobs:
  include:
    - stage: test
      node_js:
        - lts/*
      script:
        - npm run cover
        - npm run check-coverage
        - npm run build
      - stage: release
      node_js: lts/*
#      script:
#        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        on:
          all_branches: true
        script:
          - npx semantic-release