sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: false
script:
  - npm run validate
api:
  secure: 'PVT0BD+CY/9T9kkw0SHM34xT5H+1rWnkJC2QqdXDrgwp72VqB516G3leKRplyHt63QR1lRQa/ZeB4SXDcua3DrqjI1wV59MwM7HWGRMxLE9NpfTxwmBzWfu5anyYDUwetz8x+TABdojn0Y6x718OWx2WfW7p5/URBK5Wy4XWsc1aSd1+lX8LHdCB45v9Q1ksM/vqU7LnxApYNoWWltiajSukZtezqWXZonjuDZmXJM93BzM/MnNCwoehy/TIC1Xk1eA4xMpjqKiVfeArLfhtfoFl81/XC+Jeek68aHmhKj6ZTvuY5afseXI8HOd2nKB1TJB9TMp4uJKMNPWyR1QE2iLHE3XMb4eqnwieYCdWhzvwmeCpb5wVQynhZhIQf3DJhbz8Gt3VL+TO0t9e3uf0YKMdEb5woMPIGTNt/HTKog2pmAtW7SdqqKEtTopNiqP5GODDKagx3zNzbWpIKP2ohHUbjueqxiUH4I4UcB8xnW0c+R7Nh1DpWrjGJ8sb7WPPEyPKBxSiS1bWgJnL45WenLjgjaxths9qNsiUfCf5eQNYBj9eoJ0qQprweha15YvtCYGoNEJV23lHdgmI6uh9zcaV5VrOZC+qkrWGBqUiTXeIKj0W1k9QQwB0/q8FzCalv0h9A1uTgIf9zeV2b3IT6p47n0w2YeoJIAC5Oyy1H6Y='

after_success:
  - npm run report-coverage
  - npm run semantic-release
