sudo: false
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
branches:
  only:
    - main
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
